### ISSUE TITLE
Issue in downloading complete VoxBlink clean dataset

### ISSUE THREAD

**Issue by ajinkyakulkarni14** [VoxBlink/ScriptsForVoxBlink#1]
As some of videos are moved as private, I was able to download in total 935962 audio samples of voxblink-clean dataset out of 1028095 (as stated in paper). Therefore, 92,133 audio samples are missing. 

Is there anyway or future plans to release audio only dataset for speaker verification task?

Or

Any other solution to this issue?

**Comment by VoxBlink** [comment]
Sorry for a late reply. We're currently organizing and uploading our resources and we can reach out to you via email if we finish this process. Please keep an eye on your email inbox. Thank you for your support.
