### ISSUE TITLE
Voxblink resource download link connection error

### ISSUE THREAD

**Issue by greatnoble** [VoxBlink/ScriptsForVoxBlink#2]
@VoxBlink 

Thank you for sharing this very valuable Dataset.

Currently, the resource download link does not seem to be connecting.

When I clicked the link to receive ./video_list and ./timestamp from the https://voxblink.github.io/ address, access was denied.

Is there a way to download ./video_list and ./timestamp?

**Comment by greatnoble** [comment]
@ajinkyakulkarni14

Did you download the ./video_list file list and ./timestamp list properly?

Could you please share it with me?

**Comment by ajinkyakulkarni14** [comment]
Yes sure I can share it with you
