### ISSUE TITLE
Request for accessing the dataset resource

### ISSUE THREAD

**Issue by GeeYangML** [VoxBlink/ScriptsForVoxBlink#4]
Hi. Thanks for the great dataset. 

How can I have access to the resources in https://drive.google.com/drive/folders/1vP8hyT_Zefj2d40JzHLAUJWy_dBjpA22?usp=drive_link ?

**Comment by BlowtheWind22** [comment]
I have the same access denied issue when trying to download the dataset.

**Comment by VoxBlink** [comment]
Try to make a request and we will soon deal with it.
